### ISSUE TITLE
`TrimAscii` does not trim leading spaces

### ISSUE THREAD

**Issue by ilya-zlobintsev** [neon-sunset/U8String#38]
The `TrimAscii` method only trims trailing spaces, not leading ones:
```csharp
using U8;
U8String data = new(" text surrounded by spaces  "u8);
Console.WriteLine($"TrimAscii: `{data.TrimAscii()}`");
```
Outputs
```
TrimAscii: ` text surrounded by spaces`
```
https://github.com/U8String/U8String/blob/80fbcc85950252c562e79de917ad756ec9336c82/Sources/U8String/U8String.Manipulation.cs#L1733

**Comment by neon-sunset** [comment]
Thanks! Fixed in https://github.com/U8String/U8String/commit/34d4cbe720ca51589724ce00c420fead5d7ef269
