### ISSUE TITLE
Correct README

### ISSUE THREAD

**Issue by FoxTes** [neon-sunset/U8String#49]
![image](https://github.com/U8String/U8String/assets/55885862/5b5fb0fb-8dfa-44cf-bab0-ca32f1c92c51)

FIx: 
```
    <PropertyGroup>
        <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);U8.Generated</InterceptorsPreviewNamespaces>
    </PropertyGroup>
```

**Comment by neon-sunset** [comment]
Thanks, fixed in https://github.com/U8String/U8String/commit/f28342bd5dc394a74afa9b5eb23a3ce9b603f1fe
